#!/usr/bin/env bash
# configure your domain zone
domain_information () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_information "$1" "www"
  domain_information "$1" "54.236.46.6"
  domain_information "$1" "52.207.187.63"
  domain_information "$1" "204.236.240.33"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
