#!/usr/bin/env bash
# Script displays numbers 1 to 100
# Displays fizzbuzz when number is multiple of 3 and 5
# Displays Fizz when number is multiple of 3
# Displays Buzz when number is multiple of 5
for number in {1..100}
do
if (( number % 15 == 0 ))
then
echo "FizzBuzz"
elif (( number % 3 == 0 ))
then
echo "Fizz"
elif (( number % 5 == 0 ))
then
echo "Buzz"
else
echo "$number"
fi
done
