#!/usr/bin/env bash
# Script displays numbers from 1 to 10
count=0
while [ $count -lt 20 ]
do
	echo "$count"
	case $count in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
done
